import 'package:flutter/material.dart';

abstract final class AppTheme {
  static ThemeData light = ThemeData(
    colorScheme: lightColorScheme,
    scaffoldBackgroundColor: Colors.white,
    appBarTheme: AppBarTheme(
      backgroundColor: Colors.white,
      shape: Border(
        bottom: BorderSide(color: Colors.grey.shade400, width: 0.6),
      ),
      elevation: 0,
      scrolledUnderElevation: 0,
      centerTitle: false,
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(50)),
    ),
    bottomNavigationBarTheme: BottomNavigationBarThemeData(
      type: BottomNavigationBarType.fixed,
      selectedItemColor: Colors.black,
      unselectedItemColor: Colors.black,
      unselectedIconTheme: IconThemeData(size: 28),
      selectedIconTheme: IconThemeData(size: 28),
      backgroundColor: Colors.white,
      elevation: 0,
    ),
  );
  static ThemeData dark = ThemeData(
    colorScheme: darkColorScheme,
    scaffoldBackgroundColor: Colors.black,
    appBarTheme: AppBarTheme(
      backgroundColor: Colors.black,
      shape: Border(
        bottom: BorderSide(color: Colors.grey.shade600, width: 0.6),
      ),
      elevation: 0,
      scrolledUnderElevation: 0,
    ),
    tabBarTheme: TabBarThemeData(labelColor: Colors.white),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(50)),
    ),
    bottomNavigationBarTheme: BottomNavigationBarThemeData(
      type: BottomNavigationBarType.fixed,
      selectedItemColor: Colors.white,
      unselectedItemColor: Colors.white,
      unselectedIconTheme: IconThemeData(size: 28),
      selectedIconTheme: IconThemeData(size: 28),
      backgroundColor: Colors.black,
      elevation: 0,
    ),
  );
}

const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF2563EB),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF2563EB),
  onPrimaryContainer: Color(0xFFFFFFFF),
  primaryFixed: Color(0xFFD2DEF8),
  primaryFixedDim: Color(0xFFA2BBF0),
  onPrimaryFixed: Color(0xFF0B2A70),
  onPrimaryFixedVariant: Color(0xFF0C3081),
  secondary: Color(0xFFF1F5F9),
  onSecondary: Color(0xFF000000),
  secondaryContainer: Color(0xFFF1F5F9),
  onSecondaryContainer: Color(0xFF000000),
  secondaryFixed: Color(0xFFFAFAFB),
  secondaryFixedDim: Color(0xFFEFF1F2),
  onSecondaryFixed: Color(0xFF2C4A67),
  onSecondaryFixedVariant: Color(0xFF406A94),
  tertiary: Color(0xFFF1F5F9),
  onTertiary: Color(0xFF000000),
  tertiaryContainer: Color(0xFFF1F5F9),
  onTertiaryContainer: Color(0xFF000000),
  tertiaryFixed: Color(0xFFFAFAFB),
  tertiaryFixedDim: Color(0xFFEFF1F2),
  onTertiaryFixed: Color(0xFF2C4A67),
  onTertiaryFixedVariant: Color(0xFF406A94),
  error: Color(0xFFEF4444),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFE6E6),
  onErrorContainer: Color(0xFF000000),
  surface: Color(0xFFFCFCFC),
  onSurface: Color(0xFF111111),
  surfaceDim: Color(0xFFE0E0E0),
  surfaceBright: Color(0xFFFDFDFD),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFF8F8F8),
  surfaceContainer: Color(0xFFF3F3F3),
  surfaceContainerHigh: Color(0xFFEDEDED),
  surfaceContainerHighest: Color(0xFFE7E7E7),
  onSurfaceVariant: Color(0xFF393939),
  outline: Color(0xFF919191),
  outlineVariant: Color(0xFFD1D1D1),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFF2A2A2A),
  onInverseSurface: Color(0xFFF1F1F1),
  inversePrimary: Color(0xFFBEE1FF),
  surfaceTint: Color(0xFF2563EB),
);

/// Dark [ColorScheme] made with FlexColorScheme v8.3.1.
/// Requires Flutter 3.22.0 or later.
const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF3B82F6),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF3B82F6),
  onPrimaryContainer: Color(0xFFFFFFFF),
  primaryFixed: Color(0xFFD2DEF8),
  primaryFixedDim: Color(0xFFA2BBF0),
  onPrimaryFixed: Color(0xFF0B2A70),
  onPrimaryFixedVariant: Color(0xFF0C3081),
  secondary: Color(0xFF1E293B),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFF1E293B),
  onSecondaryContainer: Color(0xFFFFFFFF),
  secondaryFixed: Color(0xFFFAFAFB),
  secondaryFixedDim: Color(0xFFEFF1F2),
  onSecondaryFixed: Color(0xFF2C4A67),
  onSecondaryFixedVariant: Color(0xFF406A94),
  tertiary: Color(0xFF1E293B),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFF1E293B),
  onTertiaryContainer: Color(0xFFFFFFFF),
  tertiaryFixed: Color(0xFFFAFAFB),
  tertiaryFixedDim: Color(0xFFEFF1F2),
  onTertiaryFixed: Color(0xFF2C4A67),
  onTertiaryFixedVariant: Color(0xFF406A94),
  error: Color(0xFF7F1D1D),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFF410F0F),
  onErrorContainer: Color(0xFFFFFFFF),
  surface: Color(0xFF080808),
  onSurface: Color(0xFFF1F1F1),
  surfaceDim: Color(0xFF060606),
  surfaceBright: Color(0xFF2C2C2C),
  surfaceContainerLowest: Color(0xFF010101),
  surfaceContainerLow: Color(0xFF0E0E0E),
  surfaceContainer: Color(0xFF151515),
  surfaceContainerHigh: Color(0xFF1D1D1D),
  surfaceContainerHighest: Color(0xFF282828),
  onSurfaceVariant: Color(0xFFCACACA),
  outline: Color(0xFF777777),
  outlineVariant: Color(0xFF414141),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFFE8E8E8),
  onInverseSurface: Color(0xFF2A2A2A),
  inversePrimary: Color(0xFF223E6B),
  surfaceTint: Color(0xFF3B82F6),
);
